# Generated by Django 5.2 on 2025-04-14 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostic_type', models.CharField(choices=[('malaria', 'Malaria Detection'), ('disease', 'Disease Prediction')], max_length=20)),
                ('result_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MalariaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='malaria_images/')),
                ('diagnostic_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='malaria_image', to='diagnostics.diagnosticresult')),
            ],
        ),
        migrations.CreateModel(
            name='SymptomInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.JSONField()),
                ('diagnostic_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_input', to='diagnostics.diagnosticresult')),
            ],
        ),
    ]
